apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/cb-technologists/environment-tech-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: technologists
    envOrganisation: cb-technologists
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: cb-technologists-bot
    promotionEngine: Prow
    prowConfig: Legacy
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://tech-lts-541ddcf9-1502-46e2-90a1-f74bc87f21d5
      classifier: default
    - bucketUrl: gs://tech-lts-541ddcf9-1502-46e2-90a1-f74bc87f21d5
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
